[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-TempETA"
version = "0.2.3"
description = "OctoPrint plugin to show estimated time remaining for printer heating (implements Issue #469)"
authors = [
    {name = "AjimaruGDR", email = "ajimaru_gdr@pm.me"}
]
readme = {file = "README.md", content-type = "text/markdown"}
license = "AGPL-3.0-only"
license-files = ["LICENSE", "AUTHORS.md"]

requires-python = ">=3.7, <4"

# any additional requirements (besides OctoPrint) should be listed here
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
octoprint_temp_eta = [
    "translations/**/*.po",
    "translations/**/*.mo",
    "translations/**/*.pot",
]

[tool.setuptools.packages.find]
include = [
    "octoprint_temp_eta",
    "octoprint_temp_eta.*"
]

[project.entry-points."octoprint.plugin"]
temp_eta = "octoprint_temp_eta"

[project.urls]
Homepage = "https://github.com/Ajimaru/OctoPrint-TempETA"
Repository = "https://github.com/Ajimaru/OctoPrint-TempETA"
Issues = "https://github.com/Ajimaru/OctoPrint-TempETA/issues"
"Original Request" = "https://github.com/OctoPrint/OctoPrint/issues/469"

[project.optional-dependencies]
develop = [
    "pytest>=7.0.0",
    "pytest-cov",
    "pre-commit",
    "black>=24.0.0",
    "isort>=5.0.0",
    "flake8>=7.0.0"
]
